"""Generated documentation pages: nothing here is written by hand.

Two families, both regenerated on every build (``builder-inited``):

1. **Wrapper pages.** ``README.md``, ``SPEC.md`` and ``LICENSING.md`` are the
   documentation and remain its source. Not a line of them is copied here: each
   page is an ``include`` directive whose start and end lines are computed *from
   the headings of the file itself*. If a section is renamed or moved, the
   wrapper follows it on the next build; if it disappears, the build stops and
   says so. The Italian site translates the included text through gettext
   (``docs/locale/it``), so the wrappers are the same in both languages.

2. **Catalogues.** Definitions, vocabularies, snapshot status: every figure
   comes from the package (the same computations as ``stratigraph-templates
   info`` and ``vocab``) or from ``registry/s3dgraphy-snapshot.json``, never
   from a typed table. Their few sentences are written here in both languages
   (``TEXT``), because they are generated, not included.

Run by hand: ``python docs/_tools/generate.py [en|it]``.
"""

from __future__ import annotations

import contextlib
import io
import json
import re
import sys
from pathlib import Path

DOCS = Path(__file__).resolve().parents[1]
ROOT = DOCS.parent
OUT = DOCS / "pages"
sys.path.insert(0, str(ROOT / "src"))

HEADING = re.compile(r"^(#{1,6})\s+(.*\S)\s*$")
BANNER = "<!-- GENERATED by docs/_tools/generate.py — do not edit: rebuilt on every build -->\n\n"

# The README sections that get a page of their own, by the start of their heading.
README = {
    "layout": "How it is laid out",
    "binding": "The binding to s3Dgraphy",
    "compiled": "The compiled form",
    "kinds": "The five kinds of definition",
    "usage": "Usage",
    "licences": "Licences",
}

TEXT = {
    "en": {
        "cli_title": "The commands, from the CLI help",
        "cli_intro": "The text below is the output of `--help`, taken from the code at build time.",
        "defs_title": "Catalogue of definitions",
        "defs_intro": ("One row per folder in `templates/`. Every row comes from "
                       "`stratigraph-templates info <id>` and from the definition's `standard` "
                       "header, read at build time."),
        "defs_head": ["definition", "title", "standard", "definition version", "invented",
                      "fields", "languages", "licence", "attribution"],
        "yes": "yes", "no": "no",
        "voc_title": "Catalogue of vocabularies",
        "voc_intro": ("The schemes in `vocabularies/schemes/` and the alignments declared in "
                      "`vocabularies/alignments/`, read from the package (`Vocabularies.load()`, "
                      "the same as `stratigraph-templates vocab`) at build time."),
        "voc_head": ["scheme", "authority", "origin", "status", "binding",
                     "alignments (with)", "used by", "licence"],
        "provisional": "provisional",
        "snap_title": "Status of the s3Dgraphy snapshot",
        "snap_intro": ("`registry/s3dgraphy-snapshot.json` is the source of `validate` and "
                       "`build`, and it is the first thing to go stale. Everything below is read "
                       "from the file at build time."),
        "snap_rows": ["taken on", "s3Dgraphy commit", "folder read", "s3Dgraphy version",
                      "node datamodel", "connections datamodel", "qualia", "em.ttl",
                      "snapshot format"],
        "dirty": " (dirty tree)", "value": "value",
        "snap_contents": "What it contains", "section": "section", "entries": "entries",
    },
    "it": {
        "cli_title": "I comandi, dall'aiuto della CLI",
        "cli_intro": "Il testo qui sotto è l'uscita di `--help`, presa dal codice al momento del build.",
        "defs_title": "Catalogo delle definizioni",
        "defs_intro": ("Una riga per ogni cartella di `templates/`. Ogni riga viene da "
                       "`stratigraph-templates info <id>` e dalla testata `standard` della "
                       "definizione, letti al momento del build."),
        "defs_head": ["definizione", "titolo", "norma", "versione della definizione",
                      "inventata", "campi", "lingue", "licenza", "attribuzione"],
        "yes": "sì", "no": "no",
        "voc_title": "Catalogo dei vocabolari",
        "voc_intro": ("Gli schemi in `vocabularies/schemes/` e gli allineamenti dichiarati in "
                      "`vocabularies/alignments/`, letti dal pacchetto (`Vocabularies.load()`, "
                      "lo stesso di `stratigraph-templates vocab`) al momento del build."),
        "voc_head": ["schema", "autorità", "origine", "stato", "binding",
                     "allineamenti (con)", "usato da", "licenza"],
        "provisional": "provvisorio",
        "snap_title": "Stato dello snapshot di s3Dgraphy",
        "snap_intro": ("`registry/s3dgraphy-snapshot.json` è la fonte di `validate` e `build`, "
                       "ed è la cosa che invecchia per prima. Tutto qui sotto è letto dal file "
                       "al momento del build."),
        "snap_rows": ["preso il", "commit di s3Dgraphy", "cartella letta",
                      "versione di s3Dgraphy", "datamodel dei nodi",
                      "datamodel delle connessioni", "qualia", "em.ttl",
                      "formato dello snapshot"],
        "dirty": " (albero sporco)", "value": "valore",
        "snap_contents": "Che cosa contiene", "section": "sezione", "entries": "voci",
    },
}


# ─── 1 · wrappers: include by section, lines computed from the headings ──────

def _lines(path: Path):
    return path.read_text(encoding="utf-8").splitlines()


def _headings(path: Path):
    """[(0-based line index, level, text)], skipping fenced code blocks."""
    out, fence = [], False
    for i, line in enumerate(_lines(path)):
        if line.lstrip().startswith("```"):
            fence = not fence
            continue
        m = None if fence else HEADING.match(line)
        if m:
            out.append((i, len(m.group(1)), m.group(2)))
    return out


def _trim(path: Path, start: int, end: int) -> int:
    """Move the end back past blank lines and the closing ``---`` of a section:
    a page of its own may not end with a transition."""
    lines = _lines(path)
    while end > start + 1 and lines[end - 1].strip() in ("", "---"):
        end -= 1
    return end


def section(path: Path, prefix: str | None):
    """Lines [start, end) of the section whose heading starts with ``prefix``.

    The section ends at the next heading of the same or a higher level.
    ``prefix=None`` is the preamble: from the top to the first level-2 heading.
    A heading that cannot be found is an error, not an empty page.
    """
    hs = _headings(path)
    n = len(_lines(path))
    if prefix is None:
        end = next((i for i, lvl, _ in hs if lvl == 2), n)
        return 0, _trim(path, 0, end)
    for k, (i, lvl, text) in enumerate(hs):
        if text.startswith(prefix):
            end = next((j for j, l2, _ in hs[k + 1:] if l2 <= lvl), n)
            return i, _trim(path, i, end)
    raise LookupError(f"{path.name}: no heading starts with {prefix!r}")


def include(src: str, span=None) -> str:
    rel = Path("..", "..", src).as_posix()          # from docs/pages/ to the root
    opts = [":relative-images:"]
    if span is not None:
        opts = [f":start-line: {span[0]}", f":end-line: {span[1]}"] + opts
    return "```{include} " + rel + "\n" + "\n".join(opts) + "\n```\n"


def page(name: str, body: str) -> None:
    (OUT / f"{name}.md").write_text(BANNER + body, encoding="utf-8")


def spec_sections():
    """The level-2 sections of SPEC.md, in file order: [(n, heading)]."""
    out = []
    for _, lvl, text in _headings(ROOT / "SPEC.md"):
        m = re.match(r"^(\d+)\s*·", text)
        if lvl == 2 and m:
            out.append((m.group(1), text))
    return out


def wrappers(lang: str) -> None:
    readme, spec = ROOT / "README.md", ROOT / "SPEC.md"
    # 1 · what it is — the README without the parts that have a page of their own
    page("what-it-is", "".join(include("README.md", section(readme, p)) + "\n" for p in (
        None, README["layout"], README["binding"], README["compiled"])))
    # 2 · the five kinds
    page("kinds", include("README.md", section(readme, README["kinds"])))
    # 3 · the specification, by its own sections
    secs = spec_sections()
    toc = "\n".join(f"spec-{n}" for n, _ in secs)
    page("spec", include("SPEC.md", section(spec, None))
         + "\n```{toctree}\n:maxdepth: 2\n\n" + toc + "\n```\n")
    for n, title in secs:
        page(f"spec-{n}", include("SPEC.md", section(spec, title)))
    # 4 · usage — the README examples, then the real help of every command
    #     (generated headings sit ONE level below «## Usage», the page title)
    page("usage", include("README.md", section(readme, README["usage"])) + "\n" + cli_reference(lang))
    # 6 · licences — the README summary, then LICENSING.md in full
    page("licences-summary", include("README.md", section(readme, README["licences"])))
    page("licensing", include("LICENSING.md"))


# ─── 2 · catalogues ──────────────────────────────────────────────────────────

def _run_cli(*argv: str) -> str:
    from stratigraph_templates.cli import main
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        try:
            main(list(argv))
        except SystemExit:
            pass
    return buf.getvalue()


def cli_reference(lang: str) -> str:
    T = TEXT[lang]
    text = _run_cli("--help")
    cmds = re.search(r"\{([a-z,-]+)\}", text).group(1).split(",")
    out = [f"### {T['cli_title']}\n", T["cli_intro"] + "\n",
           "```text\n" + text.rstrip() + "\n```\n"]
    for c in cmds:
        out.append(f"#### `{c}`\n\n```text\n" + _run_cli(c, "--help").rstrip() + "\n```\n")
    return "\n".join(out)


def _md_table(head, rows) -> str:
    esc = lambda v: str(v if v is not None else "—").replace("|", "\\|").replace("\n", " ")
    lines = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    lines += ["| " + " | ".join(esc(v) for v in r) + " |" for r in rows]
    return "\n".join(lines) + "\n"


def catalogue_definitions(lang: str) -> None:
    from stratigraph_templates.cli import _all_template_ids
    from stratigraph_templates.loader import find_template
    T = TEXT[lang]
    rows = []
    for tid in _all_template_ids():
        info = json.loads(_run_cli("info", tid))          # the same computation as the command
        t = find_template(tid)
        s = t.standard
        title = s.title.get(lang) or s.title.get(t.source_language) or next(iter(s.title.values()), "")
        rows.append([f"`{tid}`", title, info["standard"], t.version,
                     T["yes"] if s.invented else T["no"], info["fields"],
                     ", ".join(info["languages"]), s.license, s.attribution])
    page("catalogue-definitions", f"# {T['defs_title']}\n\n{T['defs_intro']}\n\n"
         + _md_table(T["defs_head"], rows))


def catalogue_vocabularies(lang: str) -> None:
    from stratigraph_templates.cli import _all_template_ids
    from stratigraph_templates.loader import find_template
    from stratigraph_templates.vocab import Vocabularies
    T = TEXT[lang]
    v = Vocabularies.load()
    used = {}
    for tid in _all_template_ids():
        for f in find_template(tid).fields:
            if f.vocabulary:
                used.setdefault(f.vocabulary.scheme, set()).add(tid)
    rows = []
    for sid, s in sorted(v.schemes.items()):
        al = [a for a in v.alignments if sid in (a.source_scheme, a.target_scheme)]
        others = sorted({a.target_scheme if a.source_scheme == sid else a.source_scheme for a in al})
        status = s.status + (" · FIXTURE" if s.fixture else "") + \
            (f" · {T['provisional']} → `{s.provisional}`" if s.provisional else "")
        rows.append([f"`{sid}`", s.authority, s.origin, status, s.binding_thes_id,
                     f"{len(al)} ({', '.join(others)})" if al else "0",
                     ", ".join(f"`{t}`" for t in sorted(used.get(sid, ()))) or "—",
                     s.license])
    page("catalogue-vocabularies", f"# {T['voc_title']}\n\n{T['voc_intro']}\n\n"
         + _md_table(T["voc_head"], rows))


def catalogue_snapshot(lang: str) -> None:
    T = TEXT[lang]
    d = json.loads((ROOT / "registry" / "s3dgraphy-snapshot.json").read_text(encoding="utf-8"))
    tf = d.get("taken_from", {})
    values = [d.get("taken_on"),
              f"`{tf.get('git_commit')}`" + (T["dirty"] if tf.get("git_dirty") else ""),
              f"`{tf.get('config_dir')}`", d.get("s3dgraphy_version"),
              d.get("node_datamodel_version"), d.get("connections_version"),
              d.get("qualia_version"), d.get("em_ttl_version"), d.get("snapshot_format")]
    meta = [[k, v] for k, v in zip(T["snap_rows"], values)]
    counts = [[f"`{k}`", len(v)] for k, v in d.items()
              if isinstance(v, (list, dict)) and k != "taken_from"]
    page("snapshot-status", f"# {T['snap_title']}\n\n{T['snap_intro']}\n\n"
         + _md_table(["", T["value"]], meta) + f"\n## {T['snap_contents']}\n\n"
         + _md_table([T["section"], T["entries"]], counts))


def main(lang: str = "en") -> None:
    lang = lang if lang in TEXT else "en"
    OUT.mkdir(exist_ok=True)
    wrappers(lang)
    catalogue_definitions(lang)
    catalogue_vocabularies(lang)
    catalogue_snapshot(lang)


if __name__ == "__main__":
    main(*(sys.argv[1:2] or ["en"]))
